spring.application.name=ms-notificacoes
server.port=8083

spring.datasource.url=${NEON_DB_URL:jdbc:postgresql://ep-shiny-bread-ajd34e46-pooler.c-3.us-east-2.aws.neon.tech/neondb?sslmode=require&channelBinding=require}
spring.datasource.username=${NEON_DB_USERNAME:neondb_owner}
spring.datasource.password=${NEON_DB_PASSWORD:npg_C4gJuYKwk7MS}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.rabbitmq.addresses=${RABBITMQ_URL:amqps://dthmaznl:yucKM3hEqNBP7IOotf3hXMi-44NtPf3_@campbell.lmq.cloudamqp.com/dthmaznl}

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
info.app.name=MS Notificacoes - Carona Segura
info.app.version=1.0.0

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
